apply plugin: 'distribution'

group = 'org.apache.kafka'
version = '4.2.0-SNAPSHOT'

repositories {
    mavenCentral()
}

// https://discuss.gradle.org/t/gradle-7-x-and-duplicatesstrategy/41045/2
// https://stackoverflow.com/questions/25752078/multiproject-gradle-duplicate-dependencies-in-distribution-zip
// https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Sync.html#org.gradle.api.tasks.Sync:duplicatesStrategy
// https://docs.gradle.org/current/dsl/org.gradle.api.tasks.AbstractCopyTask.html#org.gradle.api.tasks.AbstractCopyTask:duplicatesStrategy
// https://docs.gradle.org/current/javadoc/org/gradle/api/file/DuplicatesStrategy.html#class-description

plugins.withType(DistributionPlugin) {
    distTar {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        //compression = Compression.GZIP
        //extension = 'tar.gz'
    }
}

configurations {
    wholeProjectDist
}

dependencies {
    //wholeProjectDist project(path: ':3pp-a-module', configuration: 'archives')
    //wholeProjectDist project(path: ':3pp-b-module', configuration: 'archives')
   // wholeProjectDist project(':application')
    //wholeProjectDist project(':list')
    //wholeProjectDist project(path: ':list', configuration: 'archives')
    //wholeProjectDist project(':utilities')
    //wholeProjectDist project(':producer')
    //wholeProjectDist project(':tools').jar
    //wholeProjectDist project(':tools').configurations.runtimeClasspath
    wholeProjectDist project(path: ':tools', configuration: 'archives')
    //wholeProjectDist project(':tools').jar
    //wholeProjectDist project(':trogdor').configurations.runtimeClasspath
    //wholeProjectDist project(':shell').jar
    //wholeProjectDist project(':shell').configurations.runtimeClasspath
    //wholeProjectDist project(':connect:api').jar
}

distributions {
    main {
        distributionBaseName = 'someName'
        contents {
            from(configurations.wholeProjectDist) { into("libs/") }
            //from(project(':tools').jar) { into("libs/") } //this is producing a duplicate
           // from(project.siteDocsTar) { into("site-docs/") }
        }
    }
}


